version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: lol_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: lol_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: